const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.video,
		C3.Behaviors.solid,
		C3.Plugins.TextBox,
		C3.Behaviors.Pin,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Orbit,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Follow,
		C3.Behaviors.Turret,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPos,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Acts.Scroll,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetAnimRepeatToFrame,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Sin.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{a_icon介紹: 0},
	{a_封面: 0},
	{a_綠盟介紹: 0},
	{a_綠盟標: 0},
	{a_團隊介紹: 0},
	{a_遊戲介紹按鈕: 0},
	{a_開始遊戲: 0},
	{DragDrop: 0},
	{a_音量旋鈕: 0},
	{a_音量條: 0},
	{a_音量背景: 0},
	{a_音量文字: 0},
	{Sine: 0},
	{a_標題手寫初版: 0},
	{MoveTo: 0},
	{b_播放暫停: 0},
	{b_視頻: 0},
	{b_觸碰感應: 0},
	{c_12複習點: 0},
	{c_14碰撞點: 0},
	{c_loading: 0},
	{c_MAP: 0},
	{c_上: 0},
	{c_下: 0},
	{Solid: 0},
	{c_公園經過點: 0},
	{c_右: 0},
	{c_地圖上建築: 0},
	{c_地圖使用說明: 0},
	{c_地圖垃圾: 0},
	{c_地圖界: 0},
	{c_地圖確認點: 0},
	{c_地圖路障三角錐: 0},
	{c_地圖路障路墩: 0},
	{c_地圖邊界: 0},
	{c_子單元2判斷點: 0},
	{c_左: 0},
	{移動到: 0},
	{d_11電子書: 0},
	{d_一: 0},
	{d_七: 0},
	{d_三: 0},
	{d_乘: 0},
	{d_九: 0},
	{d_二: 0},
	{d_五: 0},
	{d_八: 0},
	{d_六: 0},
	{d_再生及非再生能源: 0},
	{d_冷氣勾: 0},
	{d_冷氣機: 0},
	{d_初級能源: 0},
	{d_加: 0},
	{d_吹風機: 0},
	{d_吹風機勾: 0},
	{d_四: 0},
	{d_天然氣: 0},
	{d_對錯: 0},
	{d_提示: 0},
	{d_文本框: 0},
	{d_文本框2: 0},
	{d_文本框3: 0},
	{d_核能: 0},
	{d_次級能源: 0},
	{d_水力: 0},
	{d_減: 0},
	{d_火力: 0},
	{d_生質能: 0},
	{d_發電字卡: 0},
	{d_確認: 0},
	{d_等於: 0},
	{d_答案: 0},
	{d_解題公式: 0},
	{d_計算機: 0},
	{d_計算機圖標: 0},
	{d_計算機顯示文字: 0},
	{d_遊戲說明: 0},
	{d_除: 0},
	{d_零: 0},
	{d_電冰箱: 0},
	{d_電冰箱勾: 0},
	{d_電子鍋勾: 0},
	{d_電腦: 0},
	{d_電腦勾: 0},
	{d_電風扇: 0},
	{d_電風扇勾: 0},
	{d_電飯鍋: 0},
	{d_風力: 0},
	{d_點: 0},
	{e_12遊戲介紹: 0},
	{e_A: 0},
	{e_B: 0},
	{e_C: 0},
	{e_D: 0},
	{e_劇情中段: 0},
	{e_劇情報紙: 0},
	{e_報紙1: 0},
	{報紙1: 0},
	{e_報紙1遮罩: 0},
	{e_報紙2: 0},
	{報紙2: 0},
	{e_報紙2遮罩: 0},
	{e_報紙3: 0},
	{報紙3: 0},
	{e_報紙3遮罩: 0},
	{e_書櫃: 0},
	{e_書櫃遊戲背景: 0},
	{e_結尾乾淨圖: 0},
	{e_背景俯視店面: 0},
	{e_背景髒店面: 0},
	{Pin: 0},
	{e_說明or提示: 0},
	{e_說明or提示2: 0},
	{StartX: 0},
	{StartY: 0},
	{e_選項A不可移: 0},
	{e_選項A可移: 0},
	{e_選項B不可移: 0},
	{e_選項B可移: 0},
	{e_選項C不可移: 0},
	{e_選項C可移: 0},
	{e_選項D不可移: 0},
	{e_選項D可移: 0},
	{e_門判斷: 0},
	{e_題目: 0},
	{f_13背景: 0},
	{f_13電子書: 0},
	{f_希臘: 0},
	{f_德國: 0},
	{f_打開手冊: 0},
	{f_日本: 0},
	{f_比利時: 0},
	{f_法國: 0},
	{f_美國: 0},
	{f_說明背景: 0},
	{g_一堆塑膠袋: 0},
	{g_一堆塑膠餐具: 0},
	{g_中島: 0},
	{g_介紹: 0},
	{g_保鮮膜: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Tween: 0},
	{g_可視點: 0},
	{g_插滿的插座: 0},
	{MX: 0},
	{MY: 0},
	{g_放大鏡: 0},
	{g_桌子: 0},
	{g_機車: 0},
	{g_燈: 0},
	{g_箱子: 0},
	{g_背景: 0},
	{g_透明牆: 0},
	{g_遊戲介紹: 0},
	{g_過度包裝食品: 0},
	{g_遮擋背景: 0},
	{g_開關: 0},
	{g_顯示: 0},
	{g_髒盤食物: 0},
	{h_CH2MAP: 0},
	{i_信封105: 0},
	{i_信封112: 0},
	{i_信封113: 0},
	{i_信封年度比較: 0},
	{i_再生能源: 0},
	{i_卷軸電子書: 0},
	{i_地熱能: 0},
	{i_太陽能: 0},
	{i_廢棄風車太陽能板背景: 0},
	{i_水力: 0},
	{i_生質能: 0},
	{i_發電按鈕: 0},
	{i_發電電子書: 0},
	{i_電子書文字: 0},
	{i_風力: 0},
	{j_問答背景: 0},
	{j_電子書: 0},
	{j_題目1: 0},
	{拖放: 0},
	{k_A1: 0},
	{k_A2: 0},
	{k_B1: 0},
	{k_B2: 0},
	{k_C1: 0},
	{k_C2: 0},
	{k_再次觀看: 0},
	{k_問號1: 0},
	{k_問號2: 0},
	{k_問號3: 0},
	{已觀看: 0},
	{觀看過被點擊: 0},
	{k_嘉義: 0},
	{k_太陽: 0},
	{k_查看其他: 0},
	{k_桃園: 0},
	{k_看過案例: 0},
	{k_背景: 0},
	{k_苗栗: 0},
	{k_農地轉用: 0},
	{正弦: 0},
	{k_關閉提示詞: 0},
	{k_離岸: 0},
	{k_離岸a: 0},
	{k_離岸b: 0},
	{k_離岸c: 0},
	{k_雲林: 0},
	{k_風力: 0},
	{k_點選提示: 0},
	{Keyboard: 0},
	{k＿A感應器: 0},
	{k＿電子書: 0},
	{k＿Ｂ感應器: 0},
	{k＿Ｃ感應器: 0},
	{l_31入關碰觸: 0},
	{l_公車站: 0},
	{l_第三單元地圖: 0},
	{l_觸碰點: 0},
	{m_告示牌: 0},
	{m_紙1: 0},
	{m_紙2: 0},
	{m_紙3: 0},
	{m_遊戲介紹: 0},
	{orientation: 0},
	{Rotate: 0},
	{m_電路配對: 0},
	{n_圖書館背景: 0},
	{n_生活A: 0},
	{n_生活轉型: 0},
	{n_產業A: 0},
	{n_產業轉型: 0},
	{n_社會A: 0},
	{n_社會轉型: 0},
	{n_能源A: 0},
	{n_能源轉型: 0},
	{淡入淡出: 0},
	{n_遊戲提示: 0},
	{n_關鍵策略圖標: 0},
	{答對: 0},
	{n_電子書: 0},
	{o_台東: 0},
	{o_提示: 0},
	{o_新北: 0},
	{o_新竹: 0},
	{o_繼續觀看: 0},
	{o_背景: 0},
	{o_觀看完畢: 0},
	{o_關閉: 0},
	{o_電子書: 0},
	{o_高雄: 0},
	{題目: 0},
	{p_困難題目: 0},
	{p_怪物: 0},
	{血量: 0},
	{要扣: 0},
	{p_怪物血條: 0},
	{p_成功與失敗: 0},
	{點擊次數: 0},
	{p_攻擊: 0},
	{p_星空背景: 0},
	{p_減血: 0},
	{已點擊: 0},
	{p_簡單答案A: 0},
	{p_簡單答案B: 0},
	{p_簡單答案C: 0},
	{p_簡單答案D: 0},
	{p_簡單題目: 0},
	{p_芸血條: 0},
	{p_防守: 0},
	{p_困難答案A: 0},
	{p_困難答案B: 0},
	{p_困難答案C: 0},
	{p_困難答案D: 0},
	{p_攻擊特效: 0},
	{p_詳解: 0},
	{w_ㄑㄩ船: 0},
	{w_中部: 0},
	{w_人魚尾: 0},
	{w_北部: 0},
	{w_南部: 0},
	{w_台灣彩色: 0},
	{Orbit: 0},
	{w_我溺水了: 0},
	{w_東部: 0},
	{Sine2: 0},
	{w_波浪: 0},
	{w_海水背景: 0},
	{w_海洋垃圾: 0},
	{w_海神書: 0},
	{w_漂流瓶: 0},
	{w_特效黑幕: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{w_雲霧: 0},
	{w_霧產生器: 0},
	{w_魚尾: 0},
	{w_第一單元: 0},
	{w_第三單元: 0},
	{w_第二單元: 0},
	{w_第四單元: 0},
	{x_上一頁: 0},
	{x_右: 0},
	{x_哈豆: 0},
	{x_左: 0},
	{x_漢堡層: 0},
	{x_目錄: 0},
	{x_設定: 0},
	{x_進地圖: 0},
	{x_遊戲說明圖標: 0},
	{x_關閉: 0},
	{x_首頁: 0},
	{y_N: 0},
	{Follow: 0},
	{y_NNNS: 0},
	{y_P小頭: 0},
	{y_YUNL: 0},
	{YUNinitWidth: 0},
	{YUNflipDir: 0},
	{y_YUNS: 0},
	{y_哈豆: 0},
	{y_女NPC: 0},
	{y_女npc小頭: 0},
	{y_小C: 0},
	{y_小p: 0},
	{y_小ㄆ: 0},
	{y_萬事通: 0},
	{z_CITY模糊: 0},
	{z_CITY背景: 0},
	{z_no: 0},
	{z_yes: 0},
	{z_前往學習: 0},
	{z_前往遊玩: 0},
	{z_否: 0},
	{z_回到地圖: 0},
	{z_完成學習: 0},
	{z_對話: 0},
	{z_對話姓名: 0},
	{z_對話框: 0},
	{z_是: 0},
	{z_確認: 0},
	{Turret: 0},
	{z_箭頭: 0},
	{z_開始遊玩: 0},
	{Mouse: 0},
	{Touch: 0},
	{AJAX: 0},
	{Array: 0},
	{Audio: 0},
	{p_防守特效: 0},
	{音樂判斷: 0},
	{音量判斷: 0},
	{varVolume: 0},
	{sliderValue: 0},
	{tindex: 0},
	{sindex: 0},
	{旋鈕X: 0},
	{CH11學習結束: 0},
	{CH12學習結束: 0},
	{CH13學習結束: 0},
	{CH14學習結束: 0},
	{click: 0},
	{從地圖進: 0},
	{對話中: 0},
	{CH: 0},
	{YUN_X座標: 0},
	{YUN_Y座標: 0},
	{地圖說明: 0},
	{startTime: 0},
	{duration: 0},
	{isTransitionRunning: 0},
	{子單元判斷: 0},
	{觀看: 0},
	{v1: 0},
	{v2: 0},
	{v3: 0},
	{ans: 0},
	{答案: 0},
	{回答正確次數: 0},
	{"12TALK": 0},
	{RainbowTextString: 0},
	{i: 0},
	{"12上下層判斷": 0},
	{漢堡角度: 0},
	{DD: 0},
	{"14TALK": 0},
	{"14click": 0},
	{"14計數": 0},
	{"14判斷": 0},
	{w_地圖參數: 0},
	{w_地圖參數判斷: 0},
	{地圖北部學習完成: 0},
	{地圖中部學習完成: 0},
	{地圖南部學習完成: 0},
	{地圖東部學習完成: 0},
	{k太陽能過關: 0},
	{k風力過關: 0},
	{k離岸過關: 0},
	{遊戲過關: 0},
	{碰沒碰: 0},
	{"23TALK": 0},
	{選單: 0},
	{電子書: 0},
	{"23測驗": 0},
	{shakingTextString: 0},
	{"212TALK": 0},
	{滾輪速度: 0},
	{正在滾: 0},
	{"31TALK": 0},
	{看沒看: 0},
	{紙: 0},
	{level1: 0},
	{level1solution: 0},
	{s: 0},
	{rotationAllowed: 0},
	{"32TALK": 0},
	{p攻擊: 0},
	{p攻擊時間: 0},
	{p攻擊間隔: 0},
	{CH4狀態判斷: 0},
	{p答題鎖定: 0}
];

self.InstanceType = {
	a_icon介紹: class extends self.ISpriteInstance {},
	a_封面: class extends self.ITiledBackgroundInstance {},
	a_綠盟介紹: class extends self.ISpriteInstance {},
	a_綠盟標: class extends self.ISpriteInstance {},
	a_團隊介紹: class extends self.ISpriteInstance {},
	a_遊戲介紹按鈕: class extends self.ISpriteInstance {},
	a_開始遊戲: class extends self.ISpriteInstance {},
	a_音量旋鈕: class extends self.ISpriteInstance {},
	a_音量條: class extends self.ISpriteInstance {},
	a_音量背景: class extends self.ISpriteInstance {},
	a_音量文字: class extends self.ITextInstance {},
	a_標題手寫初版: class extends self.ISpriteInstance {},
	b_播放暫停: class extends self.ISpriteInstance {},
	b_視頻: class extends self.IWorldInstance {},
	b_觸碰感應: class extends self.ISpriteInstance {},
	c_12複習點: class extends self.ISpriteInstance {},
	c_14碰撞點: class extends self.ISpriteInstance {},
	c_loading: class extends self.ISpriteInstance {},
	c_MAP: class extends self.ITiledBackgroundInstance {},
	c_上: class extends self.ISpriteInstance {},
	c_下: class extends self.ISpriteInstance {},
	c_公園經過點: class extends self.ISpriteInstance {},
	c_右: class extends self.ISpriteInstance {},
	c_地圖上建築: class extends self.ITiledBackgroundInstance {},
	c_地圖使用說明: class extends self.ISpriteInstance {},
	c_地圖垃圾: class extends self.ISpriteInstance {},
	c_地圖界: class extends self.ISpriteInstance {},
	c_地圖確認點: class extends self.ISpriteInstance {},
	c_地圖路障三角錐: class extends self.ISpriteInstance {},
	c_地圖路障路墩: class extends self.ISpriteInstance {},
	c_地圖邊界: class extends self.ISpriteInstance {},
	c_子單元2判斷點: class extends self.ISpriteInstance {},
	c_左: class extends self.ISpriteInstance {},
	d_11電子書: class extends self.ISpriteInstance {},
	d_一: class extends self.ISpriteInstance {},
	d_七: class extends self.ISpriteInstance {},
	d_三: class extends self.ISpriteInstance {},
	d_乘: class extends self.ISpriteInstance {},
	d_九: class extends self.ISpriteInstance {},
	d_二: class extends self.ISpriteInstance {},
	d_五: class extends self.ISpriteInstance {},
	d_八: class extends self.ISpriteInstance {},
	d_六: class extends self.ISpriteInstance {},
	d_再生及非再生能源: class extends self.ISpriteInstance {},
	d_冷氣勾: class extends self.ISpriteInstance {},
	d_冷氣機: class extends self.ISpriteInstance {},
	d_初級能源: class extends self.ISpriteInstance {},
	d_加: class extends self.ISpriteInstance {},
	d_吹風機: class extends self.ISpriteInstance {},
	d_吹風機勾: class extends self.ISpriteInstance {},
	d_四: class extends self.ISpriteInstance {},
	d_天然氣: class extends self.ISpriteInstance {},
	d_對錯: class extends self.ISpriteInstance {},
	d_提示: class extends self.ISpriteInstance {},
	d_文本框: class extends self.ITextInputInstance {},
	d_文本框2: class extends self.ITextInputInstance {},
	d_文本框3: class extends self.ITextInputInstance {},
	d_核能: class extends self.ISpriteInstance {},
	d_次級能源: class extends self.ISpriteInstance {},
	d_水力: class extends self.ISpriteInstance {},
	d_減: class extends self.ISpriteInstance {},
	d_火力: class extends self.ISpriteInstance {},
	d_生質能: class extends self.ISpriteInstance {},
	d_發電字卡: class extends self.ISpriteInstance {},
	d_確認: class extends self.ISpriteInstance {},
	d_等於: class extends self.ISpriteInstance {},
	d_答案: class extends self.ITextInstance {},
	d_解題公式: class extends self.ISpriteInstance {},
	d_計算機: class extends self.ISpriteInstance {},
	d_計算機圖標: class extends self.ISpriteInstance {},
	d_計算機顯示文字: class extends self.ITextInstance {},
	d_遊戲說明: class extends self.ISpriteInstance {},
	d_除: class extends self.ISpriteInstance {},
	d_零: class extends self.ISpriteInstance {},
	d_電冰箱: class extends self.ISpriteInstance {},
	d_電冰箱勾: class extends self.ISpriteInstance {},
	d_電子鍋勾: class extends self.ISpriteInstance {},
	d_電腦: class extends self.ISpriteInstance {},
	d_電腦勾: class extends self.ISpriteInstance {},
	d_電風扇: class extends self.ISpriteInstance {},
	d_電風扇勾: class extends self.ISpriteInstance {},
	d_電飯鍋: class extends self.ISpriteInstance {},
	d_風力: class extends self.ISpriteInstance {},
	d_點: class extends self.ISpriteInstance {},
	e_12遊戲介紹: class extends self.ISpriteInstance {},
	e_A: class extends self.ITextInstance {},
	e_B: class extends self.ITextInstance {},
	e_C: class extends self.ITextInstance {},
	e_D: class extends self.ITextInstance {},
	e_劇情中段: class extends self.ITiledBackgroundInstance {},
	e_劇情報紙: class extends self.ISpriteInstance {},
	e_報紙1: class extends self.ITiledBackgroundInstance {},
	e_報紙1遮罩: class extends self.ISpriteInstance {},
	e_報紙2: class extends self.ITiledBackgroundInstance {},
	e_報紙2遮罩: class extends self.ISpriteInstance {},
	e_報紙3: class extends self.ITiledBackgroundInstance {},
	e_報紙3遮罩: class extends self.ISpriteInstance {},
	e_書櫃: class extends self.ITiledBackgroundInstance {},
	e_書櫃遊戲背景: class extends self.ITiledBackgroundInstance {},
	e_結尾乾淨圖: class extends self.ISpriteInstance {},
	e_背景俯視店面: class extends self.ITiledBackgroundInstance {},
	e_背景髒店面: class extends self.ITiledBackgroundInstance {},
	e_說明or提示: class extends self.ITextInstance {},
	e_說明or提示2: class extends self.ITextInstance {},
	e_選項A不可移: class extends self.ISpriteInstance {},
	e_選項A可移: class extends self.ISpriteInstance {},
	e_選項B不可移: class extends self.ISpriteInstance {},
	e_選項B可移: class extends self.ISpriteInstance {},
	e_選項C不可移: class extends self.ISpriteInstance {},
	e_選項C可移: class extends self.ISpriteInstance {},
	e_選項D不可移: class extends self.ISpriteInstance {},
	e_選項D可移: class extends self.ISpriteInstance {},
	e_門判斷: class extends self.ISpriteInstance {},
	e_題目: class extends self.ITextInstance {},
	f_13背景: class extends self.ISpriteInstance {},
	f_13電子書: class extends self.ISpriteInstance {},
	f_希臘: class extends self.ISpriteInstance {},
	f_德國: class extends self.ISpriteInstance {},
	f_打開手冊: class extends self.ISpriteInstance {},
	f_日本: class extends self.ISpriteInstance {},
	f_比利時: class extends self.ISpriteInstance {},
	f_法國: class extends self.ISpriteInstance {},
	f_美國: class extends self.ISpriteInstance {},
	f_說明背景: class extends self.ISpriteInstance {},
	g_一堆塑膠袋: class extends self.ISpriteInstance {},
	g_一堆塑膠餐具: class extends self.ISpriteInstance {},
	g_中島: class extends self.ISpriteInstance {},
	g_介紹: class extends self.ISpriteInstance {},
	g_保鮮膜: class extends self.ISpriteInstance {},
	g_可視點: class extends self.ISpriteInstance {},
	g_插滿的插座: class extends self.ISpriteInstance {},
	g_放大鏡: class extends self.ISpriteInstance {},
	g_桌子: class extends self.ISpriteInstance {},
	g_機車: class extends self.ISpriteInstance {},
	g_燈: class extends self.ISpriteInstance {},
	g_箱子: class extends self.ISpriteInstance {},
	g_背景: class extends self.ITiledBackgroundInstance {},
	g_透明牆: class extends self.ISpriteInstance {},
	g_遊戲介紹: class extends self.ISpriteInstance {},
	g_過度包裝食品: class extends self.ISpriteInstance {},
	g_遮擋背景: class extends self.ISpriteInstance {},
	g_開關: class extends self.ISpriteInstance {},
	g_顯示: class extends self.ITextInstance {},
	g_髒盤食物: class extends self.ISpriteInstance {},
	h_CH2MAP: class extends self.ITiledBackgroundInstance {},
	i_信封105: class extends self.ISpriteInstance {},
	i_信封112: class extends self.ISpriteInstance {},
	i_信封113: class extends self.ISpriteInstance {},
	i_信封年度比較: class extends self.ISpriteInstance {},
	i_再生能源: class extends self.ISpriteInstance {},
	i_卷軸電子書: class extends self.ISpriteInstance {},
	i_地熱能: class extends self.ISpriteInstance {},
	i_太陽能: class extends self.ISpriteInstance {},
	i_廢棄風車太陽能板背景: class extends self.ISpriteInstance {},
	i_水力: class extends self.ISpriteInstance {},
	i_生質能: class extends self.ISpriteInstance {},
	i_發電按鈕: class extends self.ISpriteInstance {},
	i_發電電子書: class extends self.ISpriteInstance {},
	i_電子書文字: class extends self.ITextInstance {},
	i_風力: class extends self.ISpriteInstance {},
	j_問答背景: class extends self.ISpriteInstance {},
	j_電子書: class extends self.ISpriteInstance {},
	j_題目1: class extends self.ITextInstance {},
	k_A1: class extends self.ISpriteInstance {},
	k_A2: class extends self.ISpriteInstance {},
	k_B1: class extends self.ISpriteInstance {},
	k_B2: class extends self.ISpriteInstance {},
	k_C1: class extends self.ISpriteInstance {},
	k_C2: class extends self.ISpriteInstance {},
	k_再次觀看: class extends self.ISpriteInstance {},
	k_問號1: class extends self.ISpriteInstance {},
	k_問號2: class extends self.ISpriteInstance {},
	k_問號3: class extends self.ISpriteInstance {},
	k_嘉義: class extends self.ISpriteInstance {},
	k_太陽: class extends self.ISpriteInstance {},
	k_查看其他: class extends self.ISpriteInstance {},
	k_桃園: class extends self.ISpriteInstance {},
	k_看過案例: class extends self.ISpriteInstance {},
	k_背景: class extends self.ISpriteInstance {},
	k_苗栗: class extends self.ISpriteInstance {},
	k_農地轉用: class extends self.ISpriteInstance {},
	k_關閉提示詞: class extends self.ISpriteInstance {},
	k_離岸: class extends self.ISpriteInstance {},
	k_離岸a: class extends self.ISpriteInstance {},
	k_離岸b: class extends self.ISpriteInstance {},
	k_離岸c: class extends self.ISpriteInstance {},
	k_雲林: class extends self.ISpriteInstance {},
	k_風力: class extends self.ISpriteInstance {},
	k_點選提示: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	k＿A感應器: class extends self.ISpriteInstance {},
	k＿電子書: class extends self.ISpriteInstance {},
	k＿Ｂ感應器: class extends self.ISpriteInstance {},
	k＿Ｃ感應器: class extends self.ISpriteInstance {},
	l_31入關碰觸: class extends self.ISpriteInstance {},
	l_公車站: class extends self.ISpriteInstance {},
	l_第三單元地圖: class extends self.ITiledBackgroundInstance {},
	l_觸碰點: class extends self.ISpriteInstance {},
	m_告示牌: class extends self.ISpriteInstance {},
	m_紙1: class extends self.ISpriteInstance {},
	m_紙2: class extends self.ISpriteInstance {},
	m_紙3: class extends self.ISpriteInstance {},
	m_遊戲介紹: class extends self.ISpriteInstance {},
	m_電路配對: class extends self.ISpriteInstance {},
	n_圖書館背景: class extends self.ISpriteInstance {},
	n_生活A: class extends self.ISpriteInstance {},
	n_生活轉型: class extends self.ISpriteInstance {},
	n_產業A: class extends self.ISpriteInstance {},
	n_產業轉型: class extends self.ISpriteInstance {},
	n_社會A: class extends self.ISpriteInstance {},
	n_社會轉型: class extends self.ISpriteInstance {},
	n_能源A: class extends self.ISpriteInstance {},
	n_能源轉型: class extends self.ISpriteInstance {},
	n_遊戲提示: class extends self.ISpriteInstance {},
	n_關鍵策略圖標: class extends self.ISpriteInstance {},
	n_電子書: class extends self.ISpriteInstance {},
	o_台東: class extends self.ISpriteInstance {},
	o_提示: class extends self.ISpriteInstance {},
	o_新北: class extends self.ISpriteInstance {},
	o_新竹: class extends self.ISpriteInstance {},
	o_繼續觀看: class extends self.ISpriteInstance {},
	o_背景: class extends self.ISpriteInstance {},
	o_觀看完畢: class extends self.ISpriteInstance {},
	o_關閉: class extends self.ISpriteInstance {},
	o_電子書: class extends self.ISpriteInstance {},
	o_高雄: class extends self.ISpriteInstance {},
	p_困難題目: class extends self.ISpriteInstance {},
	p_怪物: class extends self.ISpriteInstance {},
	p_怪物血條: class extends self.ISpriteInstance {},
	p_成功與失敗: class extends self.ISpriteInstance {},
	p_攻擊: class extends self.ISpriteInstance {},
	p_星空背景: class extends self.ITiledBackgroundInstance {},
	p_減血: class extends self.ISpriteInstance {},
	p_簡單答案A: class extends self.ISpriteInstance {},
	p_簡單答案B: class extends self.ISpriteInstance {},
	p_簡單答案C: class extends self.ISpriteInstance {},
	p_簡單答案D: class extends self.ISpriteInstance {},
	p_簡單題目: class extends self.ISpriteInstance {},
	p_芸血條: class extends self.ISpriteInstance {},
	p_防守: class extends self.ISpriteInstance {},
	p_困難答案A: class extends self.ISpriteInstance {},
	p_困難答案B: class extends self.ISpriteInstance {},
	p_困難答案C: class extends self.ISpriteInstance {},
	p_困難答案D: class extends self.ISpriteInstance {},
	p_攻擊特效: class extends self.ISpriteInstance {},
	p_詳解: class extends self.ISpriteInstance {},
	w_ㄑㄩ船: class extends self.ISpriteInstance {},
	w_中部: class extends self.ISpriteInstance {},
	w_人魚尾: class extends self.ISpriteInstance {},
	w_北部: class extends self.ISpriteInstance {},
	w_南部: class extends self.ISpriteInstance {},
	w_台灣彩色: class extends self.ISpriteInstance {},
	w_我溺水了: class extends self.ISpriteInstance {},
	w_東部: class extends self.ISpriteInstance {},
	w_波浪: class extends self.ISpriteInstance {},
	w_海水背景: class extends self.ITiledBackgroundInstance {},
	w_海洋垃圾: class extends self.ISpriteInstance {},
	w_海神書: class extends self.ISpriteInstance {},
	w_漂流瓶: class extends self.ISpriteInstance {},
	w_特效黑幕: class extends self.ISpriteInstance {},
	w_雲霧: class extends self.ISpriteInstance {},
	w_霧產生器: class extends self.ISpriteInstance {},
	w_魚尾: class extends self.ISpriteInstance {},
	w_第一單元: class extends self.ISpriteInstance {},
	w_第三單元: class extends self.ISpriteInstance {},
	w_第二單元: class extends self.ISpriteInstance {},
	w_第四單元: class extends self.ISpriteInstance {},
	x_上一頁: class extends self.ISpriteInstance {},
	x_右: class extends self.ISpriteInstance {},
	x_哈豆: class extends self.ISpriteInstance {},
	x_左: class extends self.ISpriteInstance {},
	x_漢堡層: class extends self.ISpriteInstance {},
	x_目錄: class extends self.ISpriteInstance {},
	x_設定: class extends self.ISpriteInstance {},
	x_進地圖: class extends self.ISpriteInstance {},
	x_遊戲說明圖標: class extends self.ISpriteInstance {},
	x_關閉: class extends self.ISpriteInstance {},
	x_首頁: class extends self.ISpriteInstance {},
	y_N: class extends self.ISpriteInstance {},
	y_NNNS: class extends self.ISpriteInstance {},
	y_P小頭: class extends self.ISpriteInstance {},
	y_YUNL: class extends self.ISpriteInstance {},
	y_YUNS: class extends self.ISpriteInstance {},
	y_哈豆: class extends self.ISpriteInstance {},
	y_女NPC: class extends self.ISpriteInstance {},
	y_女npc小頭: class extends self.ISpriteInstance {},
	y_小C: class extends self.ISpriteInstance {},
	y_小p: class extends self.ISpriteInstance {},
	y_小ㄆ: class extends self.ISpriteInstance {},
	y_萬事通: class extends self.ISpriteInstance {},
	z_CITY模糊: class extends self.ITiledBackgroundInstance {},
	z_CITY背景: class extends self.ITiledBackgroundInstance {},
	z_no: class extends self.ISpriteInstance {},
	z_yes: class extends self.ISpriteInstance {},
	z_前往學習: class extends self.ISpriteInstance {},
	z_前往遊玩: class extends self.ISpriteInstance {},
	z_否: class extends self.ISpriteInstance {},
	z_回到地圖: class extends self.ISpriteInstance {},
	z_完成學習: class extends self.ISpriteInstance {},
	z_對話: class extends self.ITextInstance {},
	z_對話姓名: class extends self.ITextInstance {},
	z_對話框: class extends self.ISpriteInstance {},
	z_是: class extends self.ISpriteInstance {},
	z_確認: class extends self.ISpriteInstance {},
	z_箭頭: class extends self.ISpriteInstance {},
	z_開始遊玩: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	p_防守特效: class extends self.ISpriteInstance {}
}